In [83]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import csv



In [84]:
#importing data
#u = pd.read_csv('user.csv')
r = pd.read_csv('Rating.csv')
#i = pd.read_csv('item.csv')

In [85]:
print(r)

       user_id  movie_id  rating  unix_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
...        ...       ...     ...             ...
99995      880       476       3       880175444
99996      716       204       5       879795543
99997      276      1090       1       874795795
99998       13       225       2       882399156
99999       12       203       3       879959583

[100000 rows x 4 columns]


In [86]:
# Rating = r[['user_id', 'movie_id', 'rating']].values

# Chuyển thành mảng numpy
Rating = r.iloc[:,:].values
Mod_Rating = Rating[:, [0,1,2]]  # user_id, movie_id, rating


In [87]:
print(Rating)

[[      196       242         3 881250949]
 [      186       302         3 891717742]
 [       22       377         1 878887116]
 ...
 [      276      1090         1 874795795]
 [       13       225         2 882399156]
 [       12       203         3 879959583]]


In [88]:
# Mod_Rating=Rating[:,[0,1,2]]
print(Mod_Rating)

[[ 196  242    3]
 [ 186  302    3]
 [  22  377    1]
 ...
 [ 276 1090    1]
 [  13  225    2]
 [  12  203    3]]


In [89]:
data = np.zeros((943,1682))
print(data)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [90]:
# print(len(Mod_Rating))
# for i in range(100000):
#     u=Mod_Rating[i,0]
#     it=Mod_Rating[i,1]
#     r=Mod_Rating[i,2]
#     data[u-1,it-1]=r
# np.savetxt('R.csv',data , delimiter=',', fmt='%10.40f')

for u, it, r_val in Mod_Rating:
    data[int(u)-1, int(it)-1] = r_val
np.savetxt('R.csv', data, delimiter=',', fmt='%d')



In [91]:
print(data)

[[5. 3. 4. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [5. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 5. 0. ... 0. 0. 0.]]


In [92]:
import random


In [93]:

# tr = np.zeros((943,1682))
# for i in range(943):
#     for j in range (1682):
#         tr[i,j]=data[i,j]
# te=np.zeros((943,1682))

# for i in range(943):
#     big=0
#     a=[]
#     for j in range (1682):
#         if(tr[i,j]>big):
#             big=tr[i,j]
#     for j in range(1682):
#         if(tr[i,j]==big):
#             a.append(j)
#     l=len(a)
#     #print(a)
#     for k in range(1):
#         r=random.randint(0,l-1)
#         print(r,end=' ')
#         val=a[r]
#         print(val)
#         te[i,val]=tr[i,val]
#         tr[i,val]=0

            
# np.savetxt('train.csv', tr, delimiter=',', fmt='%10.40f')
# np.savetxt('test.csv', te, delimiter=',', fmt='%10.40f')


# Chia train/test
tr = data.copy()
te = np.zeros_like(data)
for i in range(943):
    rated = np.where(tr[i, :] > 0)[0]
    if len(rated) > 0:
        max_rating = np.max(tr[i, rated])
        max_indices = rated[tr[i, rated] == max_rating]
        val = np.random.choice(max_indices)
        te[i, val] = tr[i, val]
        tr[i, val] = 0
np.savetxt('train.csv', tr, delimiter=',', fmt='%d')
np.savetxt('test.csv', te, delimiter=',', fmt='%d')

In [94]:
# #normalisation of the rating matrix
# norm=np.zeros((943,1683))
# for i in range(943):
#     sum=0
#     c=0
#     for j in range(1682):
#         norm[i,j]=tr[i,j]
#         if(tr[i,j]!=0):
#             sum+=tr[i,j]
#             c+=1
#     norm[i,1682]=(sum/c)
# for i in range(943):
#     for j in range(1682):
#         if(norm[i,j]!=0):
#             norm[i,j]=norm[i,j]-norm[i,1682]
        
# np.savetxt('norm.csv', norm, delimiter=',', fmt='%10.40f')


# Chuẩn hóa ma trận
norm = tr.copy()
user_means = np.zeros(943)
for i in range(943):
    ratings = tr[i, tr[i, :] > 0]
    user_means[i] = np.mean(ratings) if ratings.size > 0 else 0
    norm[i, tr[i, :] > 0] -= user_means[i]
np.savetxt('norm.csv', norm, delimiter=',', fmt='%6f')


In [95]:
#similarity calculations w/o normalisation
#ver1 - no sklearn fw - only loop
# import math
# cossim=np.zeros((1682,1682))
              
# for i in range(1682):
#     for j in range(i,1682):
#         num=0
#         d1=0
#         d2=0
#         for k in range(943):
#             num+=tr[k,i]*tr[k,j]
#             d1+=math.pow(tr[k,i],2)
#             d2+=math.pow(tr[k,j],2)
#         s=num/((math.sqrt(d1))*(math.sqrt(d2)))
#         cossim[i,j]=s
#         cossim[j,i]=s
#     print(i)
# print(cossim)
# np.savetxt('cossim.csv', cossim, delimiter=',', fmt='%10.40f')


#ver 2 : use sklearn fw (vector insteadof loop -> faster)
from sklearn.metrics.pairwise import cosine_similarity
cossim = cosine_similarity(tr.T)  # tr.T để tính theo items
np.savetxt('cossim.csv', cossim, delimiter=',', fmt='%10.6f')  # Giảm độ chính xác để nhanh hơn


In [96]:
#similarity calculations w normalisation
# import math
# ncossim=np.zeros((1682,1682))
              
# for i in range(1682):
#     for j in range(i,1682):
#         num=0
#         d1=0
#         d2=0
#         for k in range(943):
#             num+=norm[k,i]*norm[k,j]
#             d1+=math.pow(norm[k,i],2)
#             d2+=math.pow(norm[k,j],2)
#         s=num/((math.sqrt(d1))*(math.sqrt(d2)))
#         ncossim[i,j]=s
#         ncossim[j,i]=s
#     print(i)
# print(ncossim)
# np.savetxt('ncossim.csv', ncossim, delimiter=',', fmt='%10.40f')


from sklearn.metrics.pairwise import cosine_similarity
ncossim = cosine_similarity(norm.T)  # norm.T để tính theo items
np.savetxt('ncossim.csv', ncossim, delimiter=',', fmt='%10.6f')



In [97]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import csv



In [98]:
# #cosine similarity neighbourhood calc w/o normalisation
# n1=np.zeros((1682,10))
# t=np.zeros((1682,1682))
# for i in range(1682):
#     for j in range(1682):
#         t[i,j]=cossim[i,j]
        
# for k in range(10):
#     for i in range(1682):
#         big=0
#         val=0
#         for j in range(1682):
#             if(t[i,j]>big and i!=j):
#                 big=t[i,j]
#                 val=j
#         n1[i,k]=(val)
#         t[i,val]=-1000
# np.savetxt('n1.csv', n1, delimiter=',', fmt='%10.40f')

# Cosine Neighborhood (không chuẩn hóa)
cossim_diag = cossim.copy()
np.fill_diagonal(cossim_diag, -1e10)
n1 = np.argsort(cossim_diag, axis=1)[:,::-1][:, :10]
np.savetxt('n1.csv', n1, delimiter=',', fmt='%d')

# #cosine similarity neighbourhood calc w normalisation
# n2=np.zeros((1682,10))
# t=np.zeros((1682,1682))
# for i in range(1682):
#     for j in range(1682):
#         t[i,j]=ncossim[i,j]
        
# for k in range(10):
#     for i in range(1682):
#         big=0
#         val=0
#         for j in range(1682):
#             if(t[i,j]>big and i!=j):
#                 big=t[i,j]
#                 val=j
#         n2[i,k]=(val)
#         t[i,val]=-1000
# np.savetxt('n2.csv', n2, delimiter=',', fmt='%10.40f')

# Cosine Neighborhood (chuẩn hóa)
ncossim_diag = ncossim.copy()
np.fill_diagonal(ncossim_diag, -1e10)
n2 = np.argsort(ncossim_diag, axis=1)[:,::-1][:, :10]
np.savetxt('n2.csv', n2, delimiter=',', fmt='%d')


In [99]:
# #Probability similarity calc w/o normalisation
# ps=np.zeros((1682,1682))

# for i in range(1682):
#     for j in range(1682):
#         num=0
#         f1=0
#         f2=0
#         for k in range(943):
#             if(tr[k,i]!=0):
#                 num+=tr[k,j]
#                 f1+=1
#             if(tr[k,j]!=0):
#                 f2+=1
#         ps[i,j]=num/(f1*(math.pow(f2,0.5)))
#     print(i)
# print(ps)
# np.savetxt('probsim.csv', ps, delimiter=',', fmt='%10.40f')

# Probability Similarity (không chuẩn hóa)
probsim = np.zeros((1682, 1682))
tr_binary = (tr > 0).astype(int)
tr_sum = np.sum(tr_binary, axis=0)
for i in range(1682):
    for j in range(i, 1682):
        intersection = np.sum(tr_binary[:,i] & tr_binary[:,j])
        union = tr_sum[i] + tr_sum[j] - intersection
        s = intersection / (union + 1e-10)
        probsim[i,j] = s
        probsim[j,i] = s
np.savetxt('probsim.csv', probsim, delimiter=',', fmt='%10.6f')


In [100]:
print(ps)

[[0.18292918 0.06489443 0.05412269 ... 0.         0.00672646 0.00672646]
 [0.14460381 0.27998391 0.08189488 ... 0.         0.02307692 0.02307692]
 [0.15257664 0.10329794 0.31974141 ... 0.         0.         0.03333333]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [125]:
# #Probability calc w normalisation
# nps=np.zeros((1682,1682))

# for i in range(1682):
#     for j in range(1682):
#         num=0
#         f1=0
#         f2=0
#         for k in range(943):
#             if(norm[k,i]!=0):
#                 num+=norm[k,j]
#                 f1+=1
#             if(norm[k,j]!=0):
#                 f2+=1
#         if(f1*(math.pow(f2,0.5))!=0):
#             nps[i,j]=num/(f1*(math.pow(f2,0.5)))
#         else:
#             nps[i,j]=0
#     print(i)
# print(nps)
# np.savetxt('nprobsim.csv', nps, delimiter=',', fmt='%10.40f')



# Probability Similarity (chuẩn hóa)

# nprobsim = np.zeros((1682, 1682))
# norm_binary = (norm != 0).astype(int)
# norm_sum = np.sum(norm_binary, axis=0)
# for i in range(1682):
#     for j in range(i, 1682):
#         intersection = np.sum(norm_binary[:,i] & norm_binary[:,j])
#         union = norm_sum[i] + norm_sum[j] - intersection
#         s = intersection / (union + 1e-10)
#         nprobsim[i,j] = s
#         nprobsim[j,i] = s
# np.savetxt('nprobsim.csv', nprobsim, delimiter=',', fmt='%6f')

# Compute nprobsim (probability similarity with normalization)
nprobsim = np.zeros((1682, 1682))
norm_binary = (norm != 0).astype(int)
norm_sum = np.sum(norm_binary, axis=0)
for i in range(1682):
    for j in range(i, 1682):
        intersection = np.sum(norm_binary[:, i] & norm_binary[:, j])
        union = norm_sum[i] + norm_sum[j] - intersection
        s = intersection / (union + 1e-10)
        nprobsim[i, j] = s
        nprobsim[j, i] = s
np.savetxt('nprobsim.csv', nprobsim, delimiter=',', fmt='%10.40f')

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import csv



In [102]:

print(norm)

[[ 1.39483395 -0.60516605  0.39483395 ...  0.          0.
   0.        ]
 [ 0.31147541  0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [ 1.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          1.5988024   0.         ...  0.          0.
   0.        ]]


In [103]:
# #probability similarity neighbourhood calc w/o normalisation
# n3=np.zeros((1682,10))
# t=np.zeros((1682,1682))
# for i in range(1682):
#     for j in range(1682):
#         t[i,j]=ps[i,j]
        
# for k in range(10):
#     for i in range(1682):
#         big=0
#         val=0
#         for j in range(1682):
#             if(t[i,j]>big and i!=j):
#                 big=t[i,j]
#                 val=j
#         n3[i,k]=(val)
#         t[i,val]=-1000
# np.savetxt('n3.csv', n3, delimiter=',', fmt='%10.40f')

# Probability Neighborhood (không chuẩn hóa)
probsim_diag = probsim.copy()
np.fill_diagonal(probsim_diag, -1e10)
n3 = np.argsort(probsim_diag, axis=1)[:,::-1][:, :10]
np.savetxt('n3.csv', n3, delimiter=',', fmt='%d')

#probability similarity neighbourhood calc w normalisation
# n4=np.zeros((1682,10))
# t=np.zeros((1682,1682))
# for i in range(1682):
#     for j in range(1682):
#         t[i,j]=nps[i,j]
        
# for k in range(10):
#     for i in range(1682):
#         big=0
#         val=0
#         for j in range(1682):
#             if(t[i,j]>big and i!=j):
#                 big=t[i,j]
#                 val=j
#         n4[i,k]=(val)
#         t[i,val]=-1000
# np.savetxt('n4.csv', n4, delimiter=',', fmt='%10.40f')

# Probability Neighborhood (chuẩn hóa)
nprobsim_diag = nprobsim.copy()
np.fill_diagonal(nprobsim_diag, -1e10)
n4 = np.argsort(nprobsim_diag, axis=1)[:,::-1][:, :10]
np.savetxt('n4.csv', n4, delimiter=',', fmt='%d')


In [104]:
# #Item-based Top_N Collaborative filtering

# U=np.zeros((943,1682))
# for i in range(943):
#     c=0
#     for j in range(1682):
#         if(tr[i,j]!=0):
#             U[i,c]=(j+1)
#             c+=1

# np.savetxt('U.csv', U, delimiter=',', fmt='%10.40f')


U = np.zeros((943,1682))
for i in range(943):
    c = 0
    for j in range(1682):
        if tr[i,j] != 0:
            U[i,c] = (j+1)
            c += 1
np.savetxt('U.csv', U, delimiter=',', fmt='%10.40f')


In [105]:

#print(k)
C=np.zeros((943,1682))
for i in range(943):
    for j in range(1682):
        C[i,j]=-1

for i in range(943):
    Un=[]
    for j in range(1682):
        if(U[i,j]!=0):
            val=U[i,j]
            for m in range(10):
                Un.append(n1[int(val-1),m])
    print(i)
    l=len(Un)
    c=0
    for n in range(l):
        ar=C[i]
        if(Un[n] not in ar):
            C[i,c]=Un[n]
            c+=1
        
print(C)
np.savetxt('C.csv', C, delimiter=',', fmt='%10.40f')


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [106]:
# #Calculating the final C
# for i in range(943):
#     for j in range(1682):
#         val=C[i,j]
#         for k in range(1682):
#             v=U[i,k]
#             if(val==v):
#                 C[i,j]=-1
#     print(i)
# print(C)
# np.savetxt('Cf.csv', C, delimiter=',', fmt='%10.40f')

import numpy as np
C_final = C.copy()  # Sao chép để không sửa ma trận gốc
for i in range(943):
    rated_items = U[i, U[i] > 0]  # Item IDs user i đã rated
    C_final[i, np.isin(C[i], rated_items)] = -1
np.savetxt('Cf.csv', C_final, delimiter=',', fmt='%d')

In [107]:
# np.savetxt('Cf.csv', C, delimiter=',', fmt='%10.40f')

In [108]:
# #Finding similarity between C and U with cosine similarity
# S=np.zeros((943,1682))

# for i in range(943):
#     c=C[i]
#     u=U[i]
#     for j in range(1682):
#         sim=[]
#         val=c[j]
#         sums=0
#         if(val>=0):
#             for k in range(1682):
#                 if((u[k]-1)>=0):
#                     v=int(u[k])-1
#                     s=cossim[int(val),int(v)]
#                     sim.append(s)
#             sim=sorted(sim, key=abs, reverse=True)
#             #print(len(sim),end=' ')
#             for l in range(10):
#                 sums+=sim[l]
#             S[i,j]=sums
#     print(i)

# np.savetxt('Csim.csv', S, delimiter=',', fmt='%10.40f')




#Finding similarity between C and U with cosine similarity
S=np.zeros((943,1682))

for i in range(943):
    c=C[i]
    u=U[i]
    for j in range(1682):
        sim=[]
        val=c[j]
        sums=0
        if(val>=0):
            for k in range(1682):
                if((u[k]-1)>=0):
                    v=int(u[k])-1
                    s=cossim[int(val),int(v)]
                    sim.append(s)
            sim=sorted(sim, key=abs, reverse=True)
            #print(len(sim),end=' ')
            for l in range(10):
                sums+=sim[l]
            S[i,j]=sums
    print(i)

np.savetxt('Csim.csv', S, delimiter=',', fmt='%10.40f')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [109]:
#Finding the top N items 
tpn=np.zeros((943,10))

Scpy=np.zeros((943,1682))
for i in range(943):
    for j in range(1682):
        Scpy[i,j]=S[i,j]


for i in range(943):
    for k in range(10):
        big=0
        val=0
        for j in range(1682):
            if(Scpy[i,j]>big):
                big=Scpy[i,j]
                val=j
        tpn[i,k]=C[i,val]
        Scpy[i,val]=-1
np.savetxt('topn.csv', tpn, delimiter=',', fmt='%10.40f')


In [110]:
#Recall calculation
rec1=0
res=0
for i in range(943):
    for j in range(10):
        val=tpn[i,j]
        if(te[i,int(val)]!=0):
            res+=1
rec1=res/943
print(rec1)

0.06998939554612937


In [111]:
#print(k)
C1=np.zeros((943,1682))
for i in range(943):
    for j in range(1682):
        C1[i,j]=-1

for i in range(943):
    Un=[]
    for j in range(1682):
        if(U[i,j]!=0):
            val=U[i,j]
            for m in range(10):
                Un.append(n2[int(val-1),m])
    print(i)
    l=len(Un)
    c=0
    for n in range(l):
        ar=C1[i]
        if(Un[n] not in ar):
            C1[i,c]=Un[n]
            c+=1
        
print(C1)
np.savetxt('C1.csv', C1, delimiter=',', fmt='%10.40f')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [112]:
# #Calculating the final C1
# for i in range(943):
#     for j in range(1682):
#         val=C1[i,j]
#         for k in range(1682):
#             v=U[i,k]
#             if(val==v):
#                 C1[i,j]=-1
#     print(i)
# print(C1)
# np.savetxt('Cf1.csv', C1, delimiter=',', fmt='%10.40f')

import numpy as np
C1_final = C1.copy()  # Sao chép để không sửa ma trận gốc
for i in range(943):
    rated_items = U[i, U[i] > 0]  # Item IDs user i đã rated
    C1_final[i, np.isin(C1[i], rated_items)] = -1
np.savetxt('Cf1.csv', C1_final, delimiter=',', fmt='%d')


In [113]:
# #Finding similarity between C and U with cosine similarity
# S1=np.zeros((943,1682))
# for i in range(943):
#     c=C1[i]
#     u=U[i]
#     for j in range(1682):
#         sim=[]
#         val=c[j]
#         sums=0
#         if(val>=0):
#             for k in range(1682):
#                 if((u[k]-1)>=0):
#                     v=int(u[k])-1
#                     s=ncossim[int(val),int(v)]
#                     sim.append(s)
#             sim=sorted(sim, reverse=True)
#             #print(sim)
#             for l in range(10):
#                 sums+=sim[l]
#             S1[i,j]=sums
#     print(i)

# np.savetxt('nCsim.csv', S1, delimiter=',', fmt='%10.40f')

import numpy as np
S1 = np.zeros((943, 1682))
for i in range(943):
    valid_c = C1_final[i, C1_final[i] >= 0].astype(int)  # Candidate items (0-based)
    rated_u = U[i, U[i] > 0].astype(int) - 1  # Rated items (0-based)
    if valid_c.size > 0 and rated_u.size > 0:
        sims = ncossim[valid_c, :][:, rated_u]  # Ma trận similarity
        top_sims = np.sort(sims, axis=1)[:, -10:][:, ::-1]  # Top-10 sim
        S1[i, np.where(C1_final[i] >= 0)[0]] = np.sum(top_sims, axis=1)  # Tổng top-10
np.savetxt('nCsim.csv', S1, delimiter=',', fmt='%6f')

In [114]:
# #Finding the top N items 
# tpn1=np.zeros((943,10))

# Scpy=np.zeros((943,1682))
# for i in range(943):
#     for j in range(1682):
#         Scpy[i,j]=S1[i,j]


# for i in range(943):
#     for k in range(10):
#         big=0
#         val=0
#         for j in range(1682):
#             if(Scpy[i,j]>big):
#                 big=Scpy[i,j]
#                 val=j
#         tpn1[i,k]=C1[i,val]
#         Scpy[i,val]=-1
#     print(i)
# np.savetxt('topn1.csv', tpn1, delimiter=',', fmt='%10.40f')


import numpy as np
top_indices = np.argsort(S1, axis=1)[:, -10:][:, ::-1]  # Top-10 chỉ số
tpn1 = C1_final[np.arange(943)[:, None], top_indices]  # Top-10 item IDs
np.savetxt('topn1.csv', tpn1, delimiter=',', fmt='%d')

In [115]:
# #Recall calculation
# rec2=0
# res=0
# for i in range(943):
#     for j in range(10):
#         val=tpn1[i,j]
#         if(te[i,int(val)]!=0):
#             res+=1
# rec2=res/943
# print(rec2)

# import numpy as np
# valid_tpn1 = tpn1[tpn1 >= 0].astype(int)  # Loại -1, chuyển sang số nguyên
# hits = np.any(te[np.arange(943)[:, None], valid_tpn1] > 0, axis=1)  # Users có hit
# rec2 = np.mean(hits)  # Recall: Tỷ lệ users có ít nhất 1 hit
# print(f"Recall (Cosine normalized): {rec2:.4f}")

import numpy as np
valid_tpn1 = tpn1[tpn1 >= 1].astype(int) - 1  # Loại < 1, chuyển sang 0-based
hits = np.any(te[np.arange(943)[:, None], valid_tpn1] > 0, axis=1)  # Users có hit
rec2 = np.mean(hits)  # Recall: Tỷ lệ users có ít nhất 1 hit
print(f"Recall (Cosine normalized): {rec2:.4f}")

Recall (Cosine normalized): 0.5122


In [116]:
#print(k)
C2=np.zeros((943,1682))
for i in range(943):
    for j in range(1682):
        C2[i,j]=-1

for i in range(943):
    Un=[]
    for j in range(1682):
        if(U[i,j]!=0):
            val=U[i,j]
            for m in range(10):
                Un.append(n3[int(val-1),m])
    print(i)
    l=len(Un)
    c=0
    for n in range(l):
        ar=C2[i]
        if(Un[n] not in ar):
            C2[i,c]=Un[n]
            c+=1
        
print(C2)
np.savetxt('C2.csv', C2, delimiter=',', fmt='%10.40f')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [117]:
# #Calculating the final C
# for i in range(943):
#     for j in range(1682):
#         val=C2[i,j]
#         for k in range(1682):
#             v=U[i,k]
#             if(val==v):
#                 C2[i,j]=-1
#     print(i)
# print(C2)
# np.savetxt('Cf2.csv', C2, delimiter=',', fmt='%10.40f')

import numpy as np
C2_final = C2.copy()  # Sao chép để không sửa ma trận gốc
for i in range(943):
    rated_items = U[i, U[i] > 0]  # Item IDs user i đã rated
    C2_final[i, np.isin(C2[i], rated_items)] = -1
np.savetxt('Cf2.csv', C2_final, delimiter=',', fmt='%d')

In [118]:
# #Finding similarity between C and U with prob similarity
# S2=np.zeros((943,1682))


# for i in range(943):
#     c=C2[i]
#     u=U[i]
#     for j in range(1682):
#         sim=[]
#         val=c[j]
#         sums=0
#         if(val>=0):
#             for k in range(1682):
#                 if((u[k]-1)>=0):
#                     v=int(u[k])-1
#                     s=ps[int(val),int(v)]
#                     sim.append(s)
#             sim=sorted(sim, key=abs, reverse=True)
#             #print(len(sim),end=' ')
#             for l in range(10):
#                 sums+=sim[l]
#             S2[i,j]=sums
#     print(i)

# np.savetxt('Csim2.csv', S2, delimiter=',', fmt='%10.40f')

import numpy as np
S2 = np.zeros((943, 1682))
for i in range(943):
    valid_c = C2_final[i, C2_final[i] >= 0].astype(int)  # Candidate items (0-based)
    rated_u = U[i, U[i] > 0].astype(int) - 1  # Rated items (0-based)
    if valid_c.size > 0 and rated_u.size > 0:
        sims = ps[valid_c, :][:, rated_u]  # Ma trận similarity
        top_sims = np.sort(np.abs(sims), axis=1)[:, -10:][:, ::-1]  # Top-10 theo |sim|
        S2[i, np.where(C2_final[i] >= 0)[0]] = np.sum(top_sims, axis=1)  # Tổng top-10
np.savetxt('Csim2.csv', S2, delimiter=',', fmt='%6f')

In [119]:
# #Finding the top N items 
# tpn2=np.zeros((943,10))

# Scpy=np.zeros((943,1682))
# for i in range(943):
#     for j in range(1682):
#         Scpy[i,j]=S2[i,j]
# print(Scpy)

# for i in range(943):
#     for k in range(10):
#         big=0
#         val=0
#         for j in range(1682):
#             if(Scpy[i,j]>big):
#                 big=Scpy[i,j]
#                 val=j
#             #print(val)
#         tpn2[i,k]=C2[i,val]
#         #print(C2[i,val])
#         Scpy[i,val]=-1
    
# np.savetxt('topn2.csv', tpn2, delimiter=',', fmt='%10.40f')


import numpy as np

tpn2 = np.zeros((943, 10))
Scpy = S2.copy()
top_indices = np.argsort(Scpy, axis=1)[:, -10:][:, ::-1]
tpn2 = C2[np.arange(943)[:, None], top_indices]
np.savetxt('topn2.csv', tpn2, delimiter=',', fmt='%10.40f')

In [120]:
#Recall calculation
rec3=0
res=0
for i in range(943):
    for j in range(10):
        val=tpn2[i,j]
        if(te[i,int(val)]!=0):
            res+=1
rec3=res/943
print(rec3)

0.07529162248144221


In [121]:
# C3=np.zeros((943,1682))
# for i in range(943):
#     for j in range(1682):
#         C3[i,j]=-1

# for i in range(943):
#     Un=[]
#     for j in range(1682):
#         if(U[i,j]!=0):
#             val=U[i,j]
#             for m in range(10):
#                 Un.append(n4[int(val-1),m])
#     print(i)
#     l=len(Un)
#     c=0
#     for n in range(l):
#         ar=C3[i]
#         if(Un[n] not in ar):
#             C3[i,c]=Un[n]
#             c+=1
        
# print(C3)
# np.savetxt('C3.csv', C3, delimiter=',', fmt='%10.40f')

import numpy as np

C3 = np.full((943, 1682), -1.0)
for i in range(943):
    rated_items = U[i, U[i] != 0].astype(int) - 1
    Un = n4[rated_items].flatten() if rated_items.size > 0 else np.array([])
    unique_Un = np.unique(Un[Un >= 0])[:1682]
    C3[i, :len(unique_Un)] = unique_Un
np.savetxt('C3.csv', C3, delimiter=',', fmt='%10.40f')

In [122]:
# #Calculating the final C
# for i in range(943):
#     for j in range(1682):
#         val=C3[i,j]
#         for k in range(1682):
#             v=U[i,k]
#             if(val==v):
#                 C3[i,j]=-1
#     print(i)
# print(C3)
# np.savetxt('Cf3.csv', C3, delimiter=',', fmt='%10.40f')

import numpy as np

C3 = C3.copy()
for i in range(943):
    mask = np.isin(C3[i], U[i, U[i] != 0])
    C3[i, mask] = -1
np.savetxt('Cf3.csv', C3, delimiter=',', fmt='%10.40f')

In [126]:
# #Finding similarity between C and U with cosine similarity
# S3=np.zeros((943,1682))


# for i in range(943):
#     c=C3[i]
#     u=U[i]
#     for j in range(1682):
#         sim=[]
#         val=c[j]
#         sums=0
#         if(val>=0):
#             for k in range(1682):
#                 if((u[k]-1)>=0):
#                     v=int(u[k])-1
#                     s=nps[int(val),int(v)]
#                     sim.append(s)
#             sim=sorted(sim, key=abs, reverse=True)
#             #print(len(sim),end=' ')
#             for l in range(10):
#                 sums+=sim[l]
#             S3[i,j]=sums
#     print(i)

# np.savetxt('Csim3.csv', S3, delimiter=',', fmt='%10.40f')


import numpy as np

# S3 = np.zeros((943, 1682))
# valid_c_mask = C3 >= 0
# valid_u_mask = U > 0
# for i in range(943):
#     valid_c = C3[i, valid_c_mask[i]].astype(int)
#     rated_u = U[i, valid_u_mask[i]].astype(int) - 1
#     if valid_c.size > 0 and rated_u.size > 0:
#         sims = nps[valid_c[:, None], rated_u].squeeze()
#         top_sims = np.sort(np.abs(sims), axis=1)[:, -10:][:, ::-1]
#         S3[i, valid_c_mask[i]] = np.sum(top_sims, axis=1)
# np.savetxt('Csim3.csv', S3, delimiter=',', fmt='%10.40f')


# Compute S3 using nprobsim
S3 = np.zeros((943, 1682))
valid_c_mask = C3 >= 0
valid_u_mask = U > 0
for i in range(943):
    valid_c = C3[i, valid_c_mask[i]].astype(int)
    rated_u = U[i, valid_u_mask[i]].astype(int) - 1
    if valid_c.size > 0 and rated_u.size > 0:
        sims = nprobsim[valid_c[:, None], rated_u].squeeze()
        top_sims = np.sort(np.abs(sims), axis=1)[:, -10:][:, ::-1]
        S3[i, valid_c_mask[i]] = np.sum(top_sims, axis=1)
np.savetxt('Csim3.csv', S3, delimiter=',', fmt='%10.40f')

In [127]:
# #Finding the top N items 
# tpn3=np.zeros((943,10))

# Scpy=np.zeros((943,1682))
# for i in range(943):
#     for j in range(1682):
#         Scpy[i,j]=S3[i,j]


# for i in range(943):
#     for k in range(10):
#         big=0
#         val=0
#         for j in range(1682):
#             if(Scpy[i,j]>big):
#                 big=Scpy[i,j]
#                 val=j
#         tpn3[i,k]=C3[i,val]
#         Scpy[i,val]=-1
# np.savetxt('topn3.csv', tpn3, delimiter=',', fmt='%10.40f')


import numpy as np

tpn3 = np.zeros((943, 10))
Scpy = S3.copy()
top_indices = np.argsort(Scpy, axis=1)[:, -10:][:, ::-1]
tpn3 = C3[np.arange(943)[:, None], top_indices]
np.savetxt('topn3.csv', tpn3, delimiter=',', fmt='%10.40f')

In [128]:
#Recall calculation
rec4=0
res=0
for i in range(943):
    for j in range(10):
        val=tpn3[i,j]
        if(te[i,int(val)]!=0):
            res+=1
rec4=res/943
print(rec4)

0.05726405090137858


In [140]:
import pandas as pd

# Tải danh sách phim (điều chỉnh đường dẫn tới file u.item)
movies = pd.read_csv('ml-100k/u.item', sep='|', encoding='latin-1', header=None, usecols=[0, 1], names=['movie_id', 'movie_name'])
movie_id_to_name = dict(zip(movies['movie_id'] - 1, movies['movie_name']))  # Chỉ số bắt đầu từ 0
name_to_movie_id = {v: k for k, v in movie_id_to_name.items()}  # Ánh xạ ngược

In [142]:
import numpy as np
import pandas as pd

# Tính độ bao phủ (recall)
rec4 = np.sum([np.any(te[i, tpn3[i].astype(int)] != 0) for i in range(943)]) / 943
print(f"Độ bao phủ: {rec4}")
np.savetxt('recall.csv', [rec4], fmt='%f')  # Lưu recall vào file

# Tải danh sách phim
try:
    movies = pd.read_csv('ml-100k/u.item', sep='|', encoding='latin-1', header=None, usecols=[0, 1], names=['movie_id', 'movie_name'])
    movie_id_to_name = dict(zip(movies['movie_id'] - 1, movies['movie_name']))
    name_to_movie_id = {v: k for k, v in movie_id_to_name.items()}
except FileNotFoundError:
    print("Lỗi: Không tìm thấy file 'ml-100k/u.item'. Vui lòng tải MovieLens 100k và cập nhật đường dẫn.")
    exit()

# Hàm tìm top-N phim tương tự
def get_top_n_similar_movies(movie_name, nprobsim, name_to_movie_id, movie_id_to_name, n=10):
    if movie_name not in name_to_movie_id:
        return f"Phim '{movie_name}' không có trong dữ liệu. Vui lòng kiểm tra tên phim (ví dụ: 'Toy Story (1995)')."
    movie_idx = name_to_movie_id[movie_name]
    sim_scores = nprobsim[movie_idx]
    top_indices = np.argsort(sim_scores)[::-1][1:n+1]
    return [movie_id_to_name[idx] for idx in top_indices]

# Nhập tên phim từ terminal
movie_name = input("Nhập tên phim (ví dụ: Toy Story (1995)): ")
n = 5
top_n_movies = get_top_n_similar_movies(movie_name, nprobsim, name_to_movie_id, movie_id_to_name, n)
print(f"Top {n} phim tương tự '{movie_name}':")
for i, movie in enumerate(top_n_movies, 1):
    print(f"{i}. {movie}")

# 1. Star Wars (1977)
# 2. Aladdin (1992)
# 3. Lion King, The (1994)
# 4. Beauty and the Beast (1991)
# 5. Cinderella (1950)


Độ bao phủ: 0.05726405090137858
Top 5 phim tương tự 'Empire Strikes Back, The (1980)':
1. Raiders of the Lost Ark (1981)
2. Indiana Jones and the Last Crusade (1989)
3. Back to the Future (1985)
4. Terminator, The (1984)
5. Terminator 2: Judgment Day (1991)
